using PanguEngine.Input;

namespace PanguEngine.Client.UI.Input;

/// <summary>
/// Provides data for a routed UI keyboard event.
/// </summary>
public sealed class UiKeyEventArgs : UiInputEventArgs
{
    internal UiKeyEventArgs(
        UiNode source,
        Key key,
        KeyModifiers modifiers,
        bool isRepeat)
        : base(source)
    {
        Key = key;
        Modifiers = modifiers;
        IsRepeat = isRepeat;
    }

    /// <summary>
    /// Gets the key associated with the event.
    /// </summary>
    public Key Key { get; }

    /// <summary>
    /// Gets the modifier keys associated with the event.
    /// </summary>
    public KeyModifiers Modifiers { get; }

    /// <summary>
    /// Gets whether the event was generated by key auto-repeat.
    /// </summary>
    public bool IsRepeat { get; }
}