<Project>
    <ItemGroup>
        <Content Include="$(MSBuildThisFileDirectory)..\assets\**\*"
                 Link="assets\%(RecursiveDir)%(Filename)%(Extension)">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <None Include="$(MSBuildThisFileDirectory)..\licenses\**\*.txt"
              Link="licenses\%(RecursiveDir)%(Filename)%(Extension)">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
</Project>
